class Fortune < ApplicationRecord

  def self.generate_seed
    Fortune.create(fortune: %s(Today it's up to you to create the peacefulness you long for.), source: " rails generate resource fortune fortune:string source:string")
    Fortune.create(fortune: %s(A friend asks only for your time not your money.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(If you refuse to accept anything but the best, you very often get it.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(A smile is your passport into the hearts of others.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(A good way to keep healthy is to eat more Chinese food.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Your high-minded principles spell success.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Hard work pays off in the future, laziness pays off now.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Change can hurt, but it leads a path to something better.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Enjoy the good luck a companion brings you.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(People are naturally attracted to you.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Hidden in a valley beside an open stream- This will be the type of place where you will find your dream.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(A chance meeting opens new doors to success and friendship.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(You learn from your mistakes... You will learn a lot today.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(If you have something good in your life, don't let it go!), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(What ever you're goal is in life, embrace it visualize it, and for it will be yours.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Your shoes will make you happy today.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(You cannot love life until you live the life you love.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Be on the lookout for coming events; They cast their shadows beforehand.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Land is always on the mind of a flying bird.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(The man or woman you desire feels the same about you.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Meeting adversity well is the source of your strength.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(A dream you have will come true.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Our deeds determine us, as much as we determine our deeds.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Never give up. You're not a failure if you don't give up.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(You will become great if you believe in yourself.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(There is no greater pleasure than seeing your loved ones prosper.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(You will marry your lover.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(A very attractive person has a message for you.), source: "http://www.fortunecookiemessage.com/archive.php")
  end
end
